// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriSmart.Data;

#nullable disable

namespace NutriSmart.Migrations
{
    [DbContext(typeof(NutriSmartDbContext))]
    [Migration("20260109135002_AddSeedDataV2")]
    partial class AddSeedDataV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriSmart.Models.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Laktoz"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fıstık"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kabuklu Deniz Ürünleri"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Yumurta"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Soya"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Bal"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Susam"
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.DietProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiyetisyenId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ogun")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiyetisyenId");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("DietPrograms");
                });

            modelBuilder.Entity("NutriSmart.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Tavuk Göğsü (100g)",
                            Icerik = "Protein zengini, yağsız et",
                            Kalori = 165
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Yulaf Ezmesi (100g)",
                            Icerik = "Lif zengini, tam tahıl",
                            Kalori = 389
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yumurta (1 adet)",
                            Icerik = "Protein ve vitamin kaynağı",
                            Kalori = 78
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Süt (1 bardak)",
                            Icerik = "Kalsiyum ve D vitamini",
                            Kalori = 149
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Elma (1 adet)",
                            Icerik = "Lif ve antioksidan",
                            Kalori = 95
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Somon (100g)",
                            Icerik = "Omega-3 yağ asitleri",
                            Kalori = 208
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Brokoli (100g)",
                            Icerik = "C vitamini ve lif",
                            Kalori = 34
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Fıstık Ezmesi (2 tbsp)",
                            Icerik = "Sağlıklı yağlar, protein",
                            Kalori = 188
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Ekmek (1 dilim)",
                            Icerik = "Karbonhidrat kaynağı",
                            Kalori = 79
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Yoğurt (1 kase)",
                            Icerik = "Probiyotik, kalsiyum",
                            Kalori = 100
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.FoodAllergy", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("FoodAllergies");

                    b.HasData(
                        new
                        {
                            FoodId = 2,
                            AllergyId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            AllergyId = 5
                        },
                        new
                        {
                            FoodId = 4,
                            AllergyId = 2
                        },
                        new
                        {
                            FoodId = 8,
                            AllergyId = 3
                        },
                        new
                        {
                            FoodId = 9,
                            AllergyId = 1
                        },
                        new
                        {
                            FoodId = 10,
                            AllergyId = 2
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("Boy")
                        .HasColumnType("real");

                    b.Property<int?>("DiyetisyenId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float?>("Kilo")
                        .HasColumnType("real");

                    b.Property<string>("ProfilResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DiyetisyenId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            Email = "admin@nutri.com",
                            IsDeleted = false,
                            ProfilResmi = "default_admin.png",
                            Rol = 0,
                            Sifre = "Admin123!",
                            Soyad = "System"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Email = "diyetisyen@nutri.com",
                            IsDeleted = false,
                            ProfilResmi = "default_user.png",
                            Rol = 1,
                            Sifre = "Diyetisyen123!",
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mehmet",
                            Boy = 175f,
                            Email = "mehmet@example.com",
                            IsDeleted = false,
                            Kilo = 80f,
                            ProfilResmi = "default_user.png",
                            Rol = 2,
                            Sifre = "Danisan123!",
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Zeynep",
                            Boy = 165f,
                            Email = "zeynep@example.com",
                            IsDeleted = false,
                            Kilo = 58f,
                            ProfilResmi = "default_user.png",
                            Rol = 2,
                            Sifre = "Danisan123!",
                            Soyad = "Kaya"
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.UserAllergy", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("UserAllergies");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            AllergyId = 2
                        },
                        new
                        {
                            UserId = 4,
                            AllergyId = 1
                        },
                        new
                        {
                            UserId = 4,
                            AllergyId = 3
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.DietProgram", b =>
                {
                    b.HasOne("NutriSmart.Models.User", "Diyetisyen")
                        .WithMany()
                        .HasForeignKey("DiyetisyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.User", "User")
                        .WithMany("DietPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diyetisyen");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriSmart.Models.FoodAllergy", b =>
                {
                    b.HasOne("NutriSmart.Models.Allergy", "Allergy")
                        .WithMany("FoodAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.Food", "Food")
                        .WithMany("FoodAllergies")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("NutriSmart.Models.User", b =>
                {
                    b.HasOne("NutriSmart.Models.User", "Diyetisyen")
                        .WithMany("Danisanlar")
                        .HasForeignKey("DiyetisyenId");

                    b.Navigation("Diyetisyen");
                });

            modelBuilder.Entity("NutriSmart.Models.UserAllergy", b =>
                {
                    b.HasOne("NutriSmart.Models.Allergy", "Allergy")
                        .WithMany("UserAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.User", "User")
                        .WithMany("UserAllergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriSmart.Models.Allergy", b =>
                {
                    b.Navigation("FoodAllergies");

                    b.Navigation("UserAllergies");
                });

            modelBuilder.Entity("NutriSmart.Models.Food", b =>
                {
                    b.Navigation("FoodAllergies");
                });

            modelBuilder.Entity("NutriSmart.Models.User", b =>
                {
                    b.Navigation("Danisanlar");

                    b.Navigation("DietPrograms");

                    b.Navigation("UserAllergies");
                });
#pragma warning restore 612, 618
        }
    }
}
