// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriSmart.Data;

#nullable disable

namespace NutriSmart.Migrations
{
    [DbContext(typeof(NutriSmartDbContext))]
    [Migration("20260112125052_AddRecipesTable")]
    partial class AddRecipesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriSmart.Models.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Laktoz"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fıstık"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kabuklu Deniz Ürünleri"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Yumurta"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Soya"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Bal"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Susam"
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.DietProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiyetisyenId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ogun")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiyetisyenId");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("DietPrograms");
                });

            modelBuilder.Entity("NutriSmart.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Elma",
                            Icerik = "100g, C Vitamini, Lif",
                            Kalori = 52,
                            ResimYolu = "apple.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Muz",
                            Icerik = "100g, Potasyum, B6",
                            Kalori = 89,
                            ResimYolu = "banana.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Portakal",
                            Icerik = "100g, C Vitamini",
                            Kalori = 47,
                            ResimYolu = "orange.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Çilek",
                            Icerik = "100g, Antioksidan",
                            Kalori = 32,
                            ResimYolu = "strawberry.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Kivi",
                            Icerik = "100g, C Vitamini",
                            Kalori = 61,
                            ResimYolu = "kiwi.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Üzüm",
                            Icerik = "100g, Şekerli",
                            Kalori = 69,
                            ResimYolu = "grapes.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Karpuz",
                            Icerik = "100g, Su oranı yüksek",
                            Kalori = 30,
                            ResimYolu = "watermelon.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Kavun",
                            Icerik = "100g, A Vitamini",
                            Kalori = 34,
                            ResimYolu = "melon.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Şeftali",
                            Icerik = "100g, Lifli",
                            Kalori = 39,
                            ResimYolu = "peach.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Armut",
                            Icerik = "100g, Lifli",
                            Kalori = 57,
                            ResimYolu = "pear.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Ananas",
                            Icerik = "100g, Bromelain",
                            Kalori = 50,
                            ResimYolu = "pineapple.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Kiraz",
                            Icerik = "100g, Antioksidan",
                            Kalori = 50,
                            ResimYolu = "cherry.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Ispanak",
                            Icerik = "100g, Demir, K Vitamini",
                            Kalori = 23,
                            ResimYolu = "spinach.jpg"
                        },
                        new
                        {
                            Id = 21,
                            Ad = "Brokoli",
                            Icerik = "100g, C Vitamini",
                            Kalori = 34,
                            ResimYolu = "broccoli.jpg"
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Havuç",
                            Icerik = "100g, A Vitamini",
                            Kalori = 41,
                            ResimYolu = "carrot.jpg"
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Domates",
                            Icerik = "100g, Likopen",
                            Kalori = 18,
                            ResimYolu = "tomato.jpg"
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Salatalık",
                            Icerik = "100g, Su oranı yüksek",
                            Kalori = 15,
                            ResimYolu = "cucumber.jpg"
                        },
                        new
                        {
                            Id = 25,
                            Ad = "Biber",
                            Icerik = "100g, C Vitamini",
                            Kalori = 20,
                            ResimYolu = "pepper.jpg"
                        },
                        new
                        {
                            Id = 26,
                            Ad = "Patlıcan",
                            Icerik = "100g, Lifli",
                            Kalori = 25,
                            ResimYolu = "eggplant.jpg"
                        },
                        new
                        {
                            Id = 27,
                            Ad = "Kabak",
                            Icerik = "100g, Düşük kalori",
                            Kalori = 17,
                            ResimYolu = "zucchini.jpg"
                        },
                        new
                        {
                            Id = 40,
                            Ad = "Tavuk Göğsü",
                            Icerik = "100g, Yüksek Protein",
                            Kalori = 165,
                            ResimYolu = "chicken_breast.jpg"
                        },
                        new
                        {
                            Id = 41,
                            Ad = "Dana Kıyma",
                            Icerik = "100g, Protein, Demir",
                            Kalori = 250,
                            ResimYolu = "beef_mince.jpg"
                        },
                        new
                        {
                            Id = 42,
                            Ad = "Somon",
                            Icerik = "100g, Omega-3",
                            Kalori = 208,
                            ResimYolu = "salmon.jpg"
                        },
                        new
                        {
                            Id = 43,
                            Ad = "Yumurta",
                            Icerik = "100g, Tam Protein",
                            Kalori = 155,
                            ResimYolu = "egg.jpg"
                        },
                        new
                        {
                            Id = 44,
                            Ad = "Ton Balığı",
                            Icerik = "100g, Protein",
                            Kalori = 132,
                            ResimYolu = "tuna.jpg"
                        },
                        new
                        {
                            Id = 50,
                            Ad = "Pirinç",
                            Icerik = "100g (pişmiş), Karbonhidrat",
                            Kalori = 130,
                            ResimYolu = "rice.jpg"
                        },
                        new
                        {
                            Id = 51,
                            Ad = "Bulgur",
                            Icerik = "100g (pişmiş), Lifli",
                            Kalori = 83,
                            ResimYolu = "bulgur.jpg"
                        },
                        new
                        {
                            Id = 52,
                            Ad = "Mercimek",
                            Icerik = "100g (pişmiş), Protein, Lif",
                            Kalori = 116,
                            ResimYolu = "lentils.jpg"
                        },
                        new
                        {
                            Id = 53,
                            Ad = "Nohut",
                            Icerik = "100g (pişmiş), Protein, Lif",
                            Kalori = 164,
                            ResimYolu = "chickpeas.jpg"
                        },
                        new
                        {
                            Id = 54,
                            Ad = "Kuru Fasulye",
                            Icerik = "100g (pişmiş), Protein, Lif",
                            Kalori = 127,
                            ResimYolu = "beans.jpg"
                        },
                        new
                        {
                            Id = 55,
                            Ad = "Makarna",
                            Icerik = "100g (pişmiş), Karbonhidrat",
                            Kalori = 131,
                            ResimYolu = "pasta.jpg"
                        },
                        new
                        {
                            Id = 60,
                            Ad = "Süt (Tam Yağlı)",
                            Icerik = "100ml, Kalsiyum",
                            Kalori = 61,
                            ResimYolu = "milk.jpg"
                        },
                        new
                        {
                            Id = 61,
                            Ad = "Yoğurt",
                            Icerik = "100g, Probiyotik",
                            Kalori = 59,
                            ResimYolu = "yogurt.jpg"
                        },
                        new
                        {
                            Id = 62,
                            Ad = "Beyaz Peynir",
                            Icerik = "100g, Protein, Kalsiyum",
                            Kalori = 310,
                            ResimYolu = "cheese_white.jpg"
                        },
                        new
                        {
                            Id = 63,
                            Ad = "Kaşar Peyniri",
                            Icerik = "100g, Protein, Yağ",
                            Kalori = 402,
                            ResimYolu = "cheese_cheddar.jpg"
                        },
                        new
                        {
                            Id = 64,
                            Ad = "Tereyağı",
                            Icerik = "100g, Yağ",
                            Kalori = 717,
                            ResimYolu = "butter.jpg"
                        },
                        new
                        {
                            Id = 70,
                            Ad = "Ceviz",
                            Icerik = "100g, Omega-3",
                            Kalori = 654,
                            ResimYolu = "walnut.jpg"
                        },
                        new
                        {
                            Id = 71,
                            Ad = "Badem",
                            Icerik = "100g, E Vitamini",
                            Kalori = 579,
                            ResimYolu = "almond.jpg"
                        },
                        new
                        {
                            Id = 72,
                            Ad = "Fıstık",
                            Icerik = "100g, Protein",
                            Kalori = 567,
                            ResimYolu = "peanut.jpg"
                        },
                        new
                        {
                            Id = 73,
                            Ad = "Çikolata (Bitter)",
                            Icerik = "100g, Antioksidan",
                            Kalori = 546,
                            ResimYolu = "chocolate_dark.jpg"
                        },
                        new
                        {
                            Id = 74,
                            Ad = "Cips",
                            Icerik = "100g, Yağlı",
                            Kalori = 536,
                            ResimYolu = "chips.jpg"
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.FoodAllergy", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("FoodAllergies");

                    b.HasData(
                        new
                        {
                            FoodId = 60,
                            AllergyId = 2
                        },
                        new
                        {
                            FoodId = 61,
                            AllergyId = 2
                        },
                        new
                        {
                            FoodId = 62,
                            AllergyId = 2
                        },
                        new
                        {
                            FoodId = 63,
                            AllergyId = 2
                        },
                        new
                        {
                            FoodId = 64,
                            AllergyId = 2
                        },
                        new
                        {
                            FoodId = 72,
                            AllergyId = 3
                        },
                        new
                        {
                            FoodId = 55,
                            AllergyId = 1
                        },
                        new
                        {
                            FoodId = 43,
                            AllergyId = 5
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HazirlamaSuresi")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Kalori")
                        .HasColumnType("int");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Malzemeler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PisirmeSuresi")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talimatlar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Mevsim Salatası",
                            EklenmeTarihi = new DateTime(2026, 1, 12, 15, 50, 52, 52, DateTimeKind.Local).AddTicks(6169),
                            HazirlamaSuresi = 10,
                            IsDeleted = false,
                            Kalori = 150,
                            Kategori = "Salata",
                            KisiSayisi = 2,
                            Malzemeler = "Kıvırcık, Domates, Salatalık, Zeytinyağı, Limon",
                            PisirmeSuresi = 0,
                            ResimYolu = "salad.jpg",
                            Talimatlar = "Tüm sebzeleri yıkayıp doğrayın. Sosu ekleyip karıştırın."
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Izgara Tavuk",
                            EklenmeTarihi = new DateTime(2026, 1, 12, 15, 50, 52, 52, DateTimeKind.Local).AddTicks(6184),
                            HazirlamaSuresi = 15,
                            IsDeleted = false,
                            Kalori = 300,
                            Kategori = "Ana Yemek",
                            KisiSayisi = 4,
                            Malzemeler = "Tavuk Göğsü, Tuz, Karabiber, Kekik",
                            PisirmeSuresi = 20,
                            ResimYolu = "grilled_chicken.jpg",
                            Talimatlar = "Tavukları baharatlayıp ızgarada her iki tarafını pişirin."
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yulaflı Smoothie",
                            EklenmeTarihi = new DateTime(2026, 1, 12, 15, 50, 52, 52, DateTimeKind.Local).AddTicks(6188),
                            HazirlamaSuresi = 5,
                            IsDeleted = false,
                            Kalori = 250,
                            Kategori = "İçecek",
                            KisiSayisi = 1,
                            Malzemeler = "Yulaf, Süt, Muz, Bal",
                            PisirmeSuresi = 0,
                            ResimYolu = "smoothie.jpg",
                            Talimatlar = "Tüm malzemeleri blenderdan geçirin."
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("Boy")
                        .HasColumnType("real");

                    b.Property<int?>("DiyetisyenId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float?>("Kilo")
                        .HasColumnType("real");

                    b.Property<string>("ProfilResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DiyetisyenId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            Email = "admin@nutri.com",
                            IsDeleted = false,
                            ProfilResmi = "default_admin.png",
                            Rol = 0,
                            Sifre = "Admin123!",
                            Soyad = "System"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Email = "diyetisyen@nutri.com",
                            IsDeleted = false,
                            ProfilResmi = "default_user.png",
                            Rol = 1,
                            Sifre = "Diyetisyen123!",
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mehmet",
                            Boy = 175f,
                            Email = "mehmet@example.com",
                            IsDeleted = false,
                            Kilo = 80f,
                            ProfilResmi = "default_user.png",
                            Rol = 2,
                            Sifre = "Danisan123!",
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Zeynep",
                            Boy = 165f,
                            Email = "zeynep@example.com",
                            IsDeleted = false,
                            Kilo = 58f,
                            ProfilResmi = "default_user.png",
                            Rol = 2,
                            Sifre = "Danisan123!",
                            Soyad = "Kaya"
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.UserAllergy", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("UserAllergies");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            AllergyId = 2
                        },
                        new
                        {
                            UserId = 4,
                            AllergyId = 1
                        },
                        new
                        {
                            UserId = 4,
                            AllergyId = 3
                        });
                });

            modelBuilder.Entity("NutriSmart.Models.DietProgram", b =>
                {
                    b.HasOne("NutriSmart.Models.User", "Diyetisyen")
                        .WithMany()
                        .HasForeignKey("DiyetisyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.User", "User")
                        .WithMany("DietPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diyetisyen");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriSmart.Models.FoodAllergy", b =>
                {
                    b.HasOne("NutriSmart.Models.Allergy", "Allergy")
                        .WithMany("FoodAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.Food", "Food")
                        .WithMany("FoodAllergies")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("NutriSmart.Models.User", b =>
                {
                    b.HasOne("NutriSmart.Models.User", "Diyetisyen")
                        .WithMany("Danisanlar")
                        .HasForeignKey("DiyetisyenId");

                    b.Navigation("Diyetisyen");
                });

            modelBuilder.Entity("NutriSmart.Models.UserAllergy", b =>
                {
                    b.HasOne("NutriSmart.Models.Allergy", "Allergy")
                        .WithMany("UserAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriSmart.Models.User", "User")
                        .WithMany("UserAllergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriSmart.Models.Allergy", b =>
                {
                    b.Navigation("FoodAllergies");

                    b.Navigation("UserAllergies");
                });

            modelBuilder.Entity("NutriSmart.Models.Food", b =>
                {
                    b.Navigation("FoodAllergies");
                });

            modelBuilder.Entity("NutriSmart.Models.User", b =>
                {
                    b.Navigation("Danisanlar");

                    b.Navigation("DietPrograms");

                    b.Navigation("UserAllergies");
                });
#pragma warning restore 612, 618
        }
    }
}
